# Generated by Django 2.2.1 on 2019-08-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('algorithm_slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('topic_link', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('hire_link', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('front_id', models.IntegerField()),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=10)),
                ('total_accept', models.IntegerField()),
                ('total_submission', models.IntegerField()),
                ('accept_rate', models.FloatField()),
                ('paid_only', models.BooleanField()),
                ('like', models.IntegerField()),
                ('dislike', models.IntegerField()),
                ('frequency', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Similar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tar_difficulty', models.CharField(max_length=10)),
                ('cur_question_slug', models.ForeignKey(on_delete=True, related_name='similar_requests_created', to='questionFilter.Question')),
                ('tar_question_slug', models.ForeignKey(on_delete=True, to='questionFilter.Question')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.IntegerField()),
                ('company_slug', models.ForeignKey(on_delete=True, to='questionFilter.Company')),
                ('question_slug', models.ForeignKey(on_delete=True, to='questionFilter.Question')),
            ],
        ),
        migrations.CreateModel(
            name='AlgorithmTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_slug', models.ForeignKey(on_delete=True, to='questionFilter.Algorithm')),
                ('question_slug', models.ForeignKey(on_delete=True, to='questionFilter.Question')),
            ],
        ),
    ]
